export const jobGroupList = [
    { value: '', label: '미정' },
    { value: '생산관리/품질관리', label: '생산관리/품질관리' },
    { value: '경영/기획/컨설팅', label: '경영/기획/컨설팅' },
    { value: '생산/제조', label: '생산/제조' },
    { value: '영업/제휴', label: '영업/제휴' },
    { value: '연구개발', label: '연구개발' },
    { value: '마케팅/시장조사', label: '마케팅/시장조사' },
    { value: '엔지니어링', label: '엔지니어링' },
    { value: '유통/무역', label: '유통/무역' },
    { value: '금융/재무', label: '금융/재무' },
    { value: 'IT/인터넷', label: 'IT/인터넷' },
    { value: '인사/총무', label: '인사/총무' },
    { value: '디자인', label: '디자인' },
    { value: '의약', label: '의약' },
    { value: '특수계층/공공', label: '특수계층/공공' },
    { value: '미디어/홍보', label: '미디어/홍보' },
    { value: '전문직', label: '전문직' },
    { value: '기타', label: '기타' },
    { value: '교육', label: '교육' },
    { value: '법률/법무', label: '법률/법무' },
];
